

team_id_dict = {
        "Arsenal": 13,
        "Man City": 167,
        "Liverpool": 26,
        "Aston Villa": 24,
        "Tottenham": 30,
        "Newcastle": 23,
        "Chelsea": 15,
        "Man Utd": 32,
        "West Ham": 29,
        "Bournemouth": 183,
        "Brighton": 211,
        "Wolves": 161,
        "Fulham": 170,
        "Crystal Palace": 162,
        "Everton": 31,
        "Brentford": 189,
        "Nottingham Forest": 174,
        "Luton": 95,
        "Burnley": 184,
        "Sheff Utd": 163,
        "Leicester": 14,
        "Leeds": 19,
        "Southampton": 18,
        "Ipswich": 165
        }

ws_us_mapping = {
        "Arsenal": "Arsenal",
        "Man City": "Manchester City",
        "Liverpool": "Liverpool",
        "Aston Villa": "Aston Villa",
        "Tottenham": "Tottenham Hotspur",
        "Newcastle": "Newcastle United",
        "Chelsea": "Chelsea",
        "Man Utd": "Manchester United",
        "West Ham": "West Ham United",
        "Bournemouth": "AFC Bournemouth",
        "Brighton": "Brighton & Hove Albion",
        "Wolves": "Wolverhampton Wanderers",
        "Fulham": "Fulham",
        "Crystal Palace": "Crystal Palace",
        "Everton": "Everton",
        "Brentford": "Brentford",
        "Nottingham Forest": "Nottingham Forest",
        "Leicester": "Leicester City",
        "Southampton": "Southampton",
        "Ipswich": "Ipswich Town"
        }

ws_fx_mapping = {
        "Arsenal": "Arsenal",
        "Man City": "Manchester City",
        "Liverpool": "Liverpool",
        "Aston Villa": "Aston Villa",
        "Tottenham": "Tottenham",
        "Newcastle": "Newcastle",
        "Chelsea": "Chelsea",
        "Man Utd": "Manchester United",
        "West Ham": "West Ham",
        "Bournemouth": "Bournemouth",
        "Brighton": "Brighton",
        "Wolves": "Wolves",
        "Fulham": "Fulham",
        "Crystal Palace": "Crystal Palace",
        "Everton": "Everton",
        "Brentford": "Brentford",
        "Nottingham Forest": "Nottingham Forest",
        "Leicester": "Leicester",
        "Southampton": "Southampton",
        "Ipswich": "Ipswich"
        }
